In [1]:
import json
import pandas as pd
import numpy as np

import re

from sqlalchemy import create_engine
import psycopg2

from config import db_password

import time

In [2]:
#  Add the clean movie function that takes in the argument, "movie".
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
        
    # combine alternate titles into one list
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                    'Hangul','Hebrew','Hepburn','Japanese','Literally',
                    'Mandarin','McCune-Reischauer','Original title','Polish',
                    'Revised Romanization','Romanized','Russian',
                    'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
        if len(alt_titles) > 0:
            movie['alt_titles'] = alt_titles

    # merge column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
            change_column_name('Adaptation by', 'Writer(s)')
            change_column_name('Country of origin', 'Country')
            change_column_name('Directed by', 'Director')
            change_column_name('Distributed by', 'Distributor')
            change_column_name('Edited by', 'Editor(s)')
            change_column_name('Length', 'Running time')
            change_column_name('Original release', 'Release date')
            change_column_name('Music by', 'Composer(s)')
            change_column_name('Produced by', 'Producer(s)')
            change_column_name('Producer', 'Producer(s)')
            change_column_name('Productioncompanies ', 'Production company(s)')
            change_column_name('Productioncompany ', 'Production company(s)')
            change_column_name('Released', 'Release Date')
            change_column_name('Release Date', 'Release date')
            change_column_name('Screen story by', 'Writer(s)')
            change_column_name('Screenplay by', 'Writer(s)')
            change_column_name('Story by', 'Writer(s)')
            change_column_name('Theme music composer', 'Composer(s)')
            change_column_name('Written by', 'Writer(s)')

    return movie

In [3]:
# 1 Add the function that takes in three arguments;
# Wikipedia data, Kaggle metadata, and MovieLens rating data (from Kaggle)
#wiki_file, kaggle_file, ratings_file 

    # Clean the running time column in the wiki_movies_df DataFrame.
def extract_transform_load(wiki_file, kaggle_file, ratings_file ):
    
    # Read in the kaggle metadata and MovieLens ratings CSV files as Pandas DataFrames.
    kaggle_metadata = pd.read_csv(kaggle_file, low_memory=False)
    ratings = pd.read_csv(ratings_file)

    # Open and read the Wikipedia data JSON file.
    with open(wiki_file, mode='r') as file:
        wiki_movies_raw = json.load(file)
    
    #  Write a list comprehension to filter out TV shows.
    wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie
                   and 'No. of episodes' not in movie]

    # Write a list comprehension to iterate through the cleaned wiki movies list
    # and call the clean_movie function on each movie.
    clean_movies = [clean_movie(movie) for movie in wiki_movies] 

    # Read in the cleaned movies list from Step 4 as a DataFrame.
    wiki_movies_df = pd.DataFrame(clean_movies)

    #  Write a try-except block to catch errors while extracting the IMDb ID using a regular expression string and
    #  dropping any imdb_id duplicates. If there is an error, capture and print the exception.
    try:
        wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')
    
        #dropping duplicates
        wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)
        
    except Exception as e:
        print(e)

    #   Write a list comprehension to keep the columns that don't have null values from the wiki_movies_df DataFrame.
    wiki_columns_to_keep=[column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

    #use the wiki_columns_to_keep to create wiki_movies_df
    wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]
    
    #  Create a variable that will hold the non-null values from the “Box office” column.
    
    box_office = wiki_movies_df['Box office'].dropna()
    
    
    #  Convert the box office data created in Step 8 to string values using the lambda and join functions.
    box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)

    #  Write a regular expression to match the six elements of "form_one" of the box office data.
    #1. A dollar sign
    #2. An arbitrary (but non-zero) number of digits
    #3. An optional decimal point
    #4. An arbitrary (but possibly zero) number of more digits
    #5. A space (maybe more than one)
    #6. The word "million" or "billion"
    form_one = r'\$\d+\.?\d*\s*[mb]illion'
   
    #  Write a regular expression to match the three elements of "form_two" of the box office data.
    form_two = r'\$\d{1,3}(?:,\d{3})+'

    #  Add the parse_dollars function.
    def parse_dollars(s):
        # if s is not a string, return NaN
        if type(s) != str:
            return np.nan

        # if input is of the form $###.# million
        if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):

            # remove dollar sign and " million"
            s = re.sub('\$|\s|[a-zA-Z]','', s)

            # convert to float and multiply by a million
            value = float(s) * 10**6

            # return value
            return value

        # if input is of the form $###.# billion
        elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

            # remove dollar sign and " billion"
            s = re.sub('\$|\s|[a-zA-Z]','', s)

            # convert to float and multiply by a billion
            value = float(s) * 10**9

            # return value
            return value

        # if input is of the form $###,###,###
        elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

            # remove dollar sign and commas
            s = re.sub('\$|,','', s)

            # convert to float
            value = float(s)

            # return value
            return value

        # otherwise, return NaN
        else:
            return np.nan
        
    #  Clean the box office column in the wiki_movies_df DataFrame.
    wiki_movies_df['box_office'] = box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
    
     #We no longer need the Box Office column, so we'll just drop that.
    wiki_movies_df.drop('Box office', axis=1, inplace=True)
  
    #Clean the budget column in the wiki_movies_df DataFrame.
    budget = wiki_movies_df['Budget'].dropna() 
    
    #Convert any lists to strings
    budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)
    
    #Remove any values between a dollar sign and a hyphen (for budgets given in ranges):
    budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)
    
    #Everything is now ready to parse the budget values
    #We can copy the line of code we used to parse the box office values, changing "box_office" to "budget"
    wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
    
    #We can also drop the original Budget column
    wiki_movies_df.drop('Budget', axis=1, inplace=True)
    
    #  Clean the release date column in the wiki_movies_df DataFrame.
    #Drop na
    #Convert any lists to strings
    release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
    
    #Get the four forms
    date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]?\d,\s\d{4}'
    date_form_two = r'\d{4}.[01]\d.[0123]\d'
    date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
    date_form_four = r'\d{4}'

    #We have all the parts to parse the Release Date column
    release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})', flags=re.IGNORECASE)
        
    # 16. Clean the running time column in the wiki_movies_df DataFrame.
    #dropna and convert to a string
    running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
   
    #Write a refular expression to match all of the hour + minute patterns with one regular expression
    #1. Start with one or more digits.
    #2. Have an optional space after the digit and before the letter "h."
    #3.Capture all the possible abbreviations of "hour(s)." To do this, we'll make every letter in "hours" optional except the "h."
    #4. Have an optional space after the "hours" marker.
    #5. Have an optional number of digits for minutes.
    #5. As a pattern, this looks like "\d+\s*ho?u?r?s?\s*\d*".
    
    running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')
    
    #we'll need to convert them to numeric values. Because we may have captured empty strings, we'll use the to_numeric() method and set the errors argument to 'coerce'.
    running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)
    
    #apply a function that will convert the hour capture groups and minute capture groups to minutes if the pure minutes capture group is zero, and save the output to wiki_movies_df:
    wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)
    
    #drop Running time from the dataset with the following code:
    wiki_movies_df.drop('Running time', axis=1, inplace=True)
    
    # Return three variables. The first is the wiki_movies_df DataFrame
    return wiki_movies_df, kaggle_metadata, ratings 

############################################################################################################################     
    # 2. Clean the Kaggle metadata.
    #keep rows where the adult column is FALSE, and then drop the adult column
    kaggle_metadata = kaggle_metadata[kaggle_metadata['adult'] == 'False'].drop('adult',axis='columns')

    #remove bad data types:video column
    kaggle_metadata['video'] = kaggle_metadata['video'] == 'True'

    #convert budget to int
    kaggle_metadata['budget'] = kaggle_metadata['budget'].astype(int)
    
    #id an d popularity to numeric
    kaggle_metadata['id'] = pd.to_numeric(kaggle_metadata['id'], errors='raise')
    kaggle_metadata['popularity'] = pd.to_numeric(kaggle_metadata['popularity'], errors='raise')
    
    #convert the release_date to datetime()
    kaggle_metadata['release_date'] = pd.to_datetime(kaggle_metadata['release_date'])
    
    # 3. Merged the two DataFrames into the movies DataFrame.
    #get only the data that is in both DataFrames (how 'inner' which is the default)
    movies_df = pd.merge(wiki_movies_df, kaggle_metadata, on='imdb_id', suffixes=['_wiki','_kaggle'])

    # 4. Drop unnecessary columns from the merged DataFrame.
    movies_df.drop(columns=['title_wiki','release_date_wiki','Language','Production company(s)'], inplace=True)

    # 5. Add in the function to fill in the missing Kaggle data.
    def fill_missing_kaggle_data(df, kaggle_column, wiki_column):
        df[kaggle_column] = df.apply(lambda row: row[wiki_column] if row[kaggle_column] == 0 else row[kaggle_column], axis=1)
        df.drop(columns=wiki_column, inplace=True)

    # 6. Call the function in Step 5 with the DataFrame and columns as the arguments.
    fill_missing_kaggle_data(movies_df, 'runtime', 'running_time')
    fill_missing_kaggle_data(movies_df, 'budget_kaggle', 'budget_wiki')
    fill_missing_kaggle_data(movies_df, 'revenue', 'box_office')
    movies_df

    # 7. Filter the movies DataFrame for specific columns.
    #Having similar columns near each other helps people looking through the data get a better sense
    #The following code is one way to reorder the columns and uses .loc and requests for all columns
    movies_df = movies_df.loc[:, ['imdb_id','id','title_kaggle','original_title','tagline','belongs_to_collection','url','imdb_link',
                       'runtime','budget_kaggle','revenue','release_date_kaggle','popularity','vote_average','vote_count',
                       'genres','original_language','overview','spoken_languages','Country',
                       'production_companies','production_countries','Distributor',
                       'Producer(s)','Director','Starring','Cinematography','Editor(s)','Writer(s)','Composer(s)','Based on'
                      ]]

    # 8. Rename the columns in the movies DataFrame.
    movies_df.rename({'id':'kaggle_id',
                  'title_kaggle':'title',
                  'url':'wikipedia_url',
                  'budget_kaggle':'budget',
                  'release_date_kaggle':'release_date',
                  'Country':'country',
                  'Distributor':'distributor',
                  'Producer(s)':'producers',
                  'Director':'director',
                  'Starring':'starring',
                  'Cinematography':'cinematography',
                  'Editor(s)':'editors',
                  'Writer(s)':'writers',
                  'Composer(s)':'composers',
                  'Based on':'based_on'
                 }, axis='columns', inplace=True)

    # 9. Transform and merge the ratings DataFrame.
    #use a groupby on movieID and ratings columns take the count
    #rename userID to count
    rating_counts = ratings.groupby(['movieId','rating'], as_index=False).count() \
                .rename({'userId':'count'}, axis=1) \
                .pivot(index='movieId',columns='rating', values='count')

    #rename the columns 
    rating_counts.columns = ['rating_' + str(col) for col in rating_counts.columns]

    #we need to keep everything in movies_df just add additional information(if available) ratings_count
    movies_with_ratings_df = pd.merge(movies_df, rating_counts, left_on='kaggle_id', right_index=True, how='left')
    
    #return wiki_movies_df, movies_with_ratings_df, movies_df

    #### Load##########################################################################################################
    db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/movie_data"
    
    #create the database engine using from sqlalchemy import create_engine
    engine = create_engine(db_string)
    
    
    #save the movies_df DataFrame to a SQL table, we ony have to specidy the name of the table and the engine in the to_sg() method
    #Use 'replace' for the if_exists parameter
    movies_df.to_sql(name='movies', con=engine, if_exists='replace')
    
    #import the ratings Data (ratings.csv file in Resources)
    rows_imported = 0

        # get the start_time from time.time()
    start_time = time.time()
    for data in pd.read_csv(f'{file_dir}ratings.csv', chunksize=1000000):
        print(f'importing rows {rows_imported} to {rows_imported + len(data)}...', end='')
        data.to_sql(name='ratings', con=engine, if_exists='append')
        rows_imported += len(data)

        # add elapsed time to final print out
        print(f'Done. {time.time() - start_time} total seconds elapsed')

In [4]:
# 10. Create the path to your file directory and variables for the three files.
file_dir = "./Resources/"
# Wikipedia data
wiki_file = f'{file_dir}/wikipedia-movies.json'
# Kaggle metadata
kaggle_file = f'{file_dir}/movies_metadata.csv'
# MovieLens rating data.
ratings_file = f'{file_dir}/ratings.csv'

In [5]:
# 11. Set the three variables equal to the function created in D1.
#wiki_file, kaggle_file, ratings_file = extract_transform_load()
extract_transform_load(wiki_file, kaggle_file, ratings_file)

(                                                    url  year  \
 0     https://en.wikipedia.org/wiki/The_Adventures_o...  1990
 1     https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990
 2      https://en.wikipedia.org/wiki/Air_America_(film)  1990
 3       https://en.wikipedia.org/wiki/Alice_(1990_film)  1990
 4         https://en.wikipedia.org/wiki/Almost_an_Angel  1990
 ...                                                 ...   ...
 7071    https://en.wikipedia.org/wiki/Holmes_%26_Watson  2018
 7072     https://en.wikipedia.org/wiki/Vice_(2018_film)  2018
 7073  https://en.wikipedia.org/wiki/On_the_Basis_of_Sex  2018
 7074  https://en.wikipedia.org/wiki/Destroyer_(2018_...  2018
 7075  https://en.wikipedia.org/wiki/Black_Mirror:_Ba...  2018

                                   imdb_link                            title  \
 0     https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane
 1     https://www.imdb.com/title/tt0098994/             After Dark, My Sweet
 2     https://www.imdb.com/title/tt0099005/                      Air America
 3     https://www.imdb.com/title/tt0099012/                            Alice
 4     https://www.imdb.com/title/tt0099018/                  Almost an Angel
 ...                                     ...                              ...
 7071  https://www.imdb.com/title/tt1255919/                  Holmes & Watson
 7072  https://www.imdb.com/title/tt6266538/                             Vice
 7073  https://www.imdb.com/title/tt4669788/              On the Basis of Sex
 7074  https://www.imdb.com/title/tt7137380/                        Destroyer
 7075  https://www.imdb.com/title/tt9495224/                     Bandersnatch

              Directed by                                        Produced by  \
 0           Renny Harlin                         [Steve Perry, Joel Silver]
 1            James Foley                        [Ric Kidney, Robert Redlin]
 2     Roger Spottiswoode                                     Daniel Melnick
 3            Woody Allen                                    Robert Greenhut
 4           John Cornell                                       John Cornell
 ...                  ...                                                ...
 7071          Etan Cohen  [Will Ferrell, Adam McKay, Jimmy Miller, Clayt...
 7072          Adam McKay  [Brad Pitt, Dede Gardner, Jeremy Kleiner, Kevi...
 7073          Mimi Leder                                     Robert W. Cort
 7074        Karyn Kusama             [Fred Berger, Phil Hay, Matt Manfredi]
 7075         David Slade                                     Russell McLean

                                    Screenplay by                     Story by  \
 0     [David Arnott, James Cappe, Daniel Waters]  [David Arnott, James Cappe]
 1                   [James Foley, Robert Redlin]                          NaN
 2                     [John Eskow, Richard Rush]                          NaN
 3                                            NaN                          NaN
 4                                            NaN                          NaN
 ...                                          ...                          ...
 7071                                  Etan Cohen                          NaN
 7072                                         NaN                          NaN
 7073                                         NaN                          NaN
 7074                                         NaN                          NaN
 7075                                         NaN                          NaN

                                                Based on  \
 0                           [Characters, by Rex Weiner]
 1     [the novel, After Dark, My Sweet, by, Jim Thom...
 2                [Air America, by, Christopher Robbins]
 3                                                   NaN
 4                                                   NaN
 ...                                                 ...
 7071  [Sherlock Holmes, and, Dr. Watson, by, Sir Art...
 7072                                                NaN
 7073                                                NaN
 7074                                                NaN
 7075                                                NaN

                                                Starring  ...  \
 0     [Andrew Dice Clay, Wayne Newton, Priscilla Pre...  ...
 1     [Jason Patric, Rachel Ward, Bruce Dern, George...  ...
 2     [Mel Gibson, Robert Downey Jr., Nancy Travis, ...  ...
 3     [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...  ...
 4           [Paul Hogan, Elias Koteas, Linda Kozlowski]  ...
 ...                                                 ...  ...
 7071  [Will Ferrell, John C. Reilly, Rebecca Hall, R...  ...
 7072  [Christian Bale, Amy Adams, Steve Carell, Sam ...  ...
 7073  [Felicity Jones, Armie Hammer, Justin Theroux,...  ...
 7074  [Nicole Kidman, Sebastian Stan, Toby Kebbell, ...  ...
 7075  [Fionn Whitehead, Will Poulter, Craig Parkinso...  ...

                Distributed by  \
 0            20th Century Fox
 1             Avenue Pictures
 2            TriStar Pictures
 3              Orion Pictures
 4          Paramount Pictures
 ...                       ...
 7071  Sony Pictures Releasing
 7072         Mirror Releasing
 7073           Focus Features
 7074         Mirror Releasing
 7075                  Netflix

                                            Release date         Country  \
 0                     [July 11, 1990, (, 1990-07-11, )]   United States
 1     [May 17, 1990, (, 1990-05-17, ), (Cannes Film ...   United States
 2                   [August 10, 1990, (, 1990-08-10, )]   United States
 3                 [December 25, 1990, (, 1990-12-25, )]   United States
 4                                     December 19, 1990              US
 ...                                                 ...             ...
 7071  [December 25, 2018, (, 2018-12-25, ), (United ...   United States
 7072  [December 11, 2018, (, 2018-12-11, ), (, Samue...   United States
 7073  [November 8, 2018, (, 2018-11-08, ), (, AFI Fe...   United States
 7074  [August 31, 2018, (, 2018-08-31, ), (, Telluri...   United States
 7075               [28 December 2018, (, 2018-12-28, )]  United Kingdom

             Language                 Written by  \
 0            English                        NaN
 1            English                        NaN
 2     [English, Lao]                        NaN
 3            English                Woody Allen
 4            English                 Paul Hogan
 ...              ...                        ...
 7071         English                        NaN
 7072         English                 Adam McKay
 7073         English          Daniel Stiepleman
 7074         English  [Phil Hay, Matt Manfredi]
 7075         English            Charlie Brooker

                                    Productioncompanies     imdb_id  \
 0                                                   NaN  tt0098987
 1                                                   NaN  tt0098994
 2                                                   NaN  tt0099005
 3                                                   NaN  tt0099012
 4                                                   NaN  tt0099018
 ...                                                 ...        ...
 7071  [Columbia Pictures, Gary Sanchez Productions, ...  tt1255919
 7072                                                NaN  tt6266538
 7073  [Focus Features, [1], Participant Media, [1], ...  tt4669788
 7074                                                NaN  tt7137380
 7075                                                NaN  tt9495224

       box_office      budget running_time
 0     21400000.0  20000000.0        102.0
 1      2700000.0   6000000.0        114.0
 2     57718089.0  35000000.0        113.0
 3      7331647.0  12000000.0        106.0
 4      6939946.0  25000000.0         95.0
 ...          ...         ...          ...
 7071  41900000.0  42000000.0         90.0
 7072  76100000.0  60000000.0        132.0
 7073  38400000.0  20000000.0        120.0
 7074   5500000.0   9000000.0        123.0
 7075         NaN         NaN         90.0

 [7033 rows x 24 columns],
        adult                              belongs_to_collection    budget  \
 0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
 1      False                                                NaN  65000000
 2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
 3      False                                                NaN  16000000
 4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0
 ...      ...                                                ...       ...
 45461  False                                                NaN         0
 45462  False                                                NaN         0
 45463  False                                                NaN         0
 45464  False                                                NaN         0
 45465  False                                                NaN         0

                                                   genres  \
 0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
 1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
 2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
 3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
 4                         [{'id': 35, 'name': 'Comedy'}]
 ...                                                  ...
 45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
 45462                      [{'id': 18, 'name': 'Drama'}]
 45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
 45464                                                 []
 45465                                                 []

                                    homepage      id    imdb_id  \
 0      http://toystory.disney.com/toy-story     862  tt0114709
 1                                       NaN    8844  tt0113497
 2                                       NaN   15602  tt0113228
 3                                       NaN   31357  tt0114885
 4                                       NaN   11862  tt0113041
 ...                                     ...     ...        ...
 45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
 45462                                   NaN  111109  tt2028550
 45463                                   NaN   67758  tt0303758
 45464                                   NaN  227506  tt0008536
 45465                                   NaN  461257  tt6980792

       original_language               original_title  \
 0                    en                    Toy Story
 1                    en                      Jumanji
 2                    en             Grumpier Old Men
 3                    en            Waiting to Exhale
 4                    en  Father of the Bride Part II
 ...                 ...                          ...
 45461                fa                      رگ خواب
 45462                tl          Siglo ng Pagluluwal
 45463                en                     Betrayal
 45464                en          Satana likuyushchiy
 45465                en                     Queerama

                                                 overview  ... release_date  \
 0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
 1      When siblings Judy and Peter discover an encha...  ...   1995-12-15
 2      A family wedding reignites the ancient feud be...  ...   1995-12-22
 3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
 4      Just when George Banks has recovered from his ...  ...   1995-02-10
 ...                                                  ...  ...          ...
 45461        Rising and falling between a man and woman.  ...          NaN
 45462  An artist struggles to finish his work while a...  ...   2011-11-17
 45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01
 45464  In a small town live two brothers, one a minis...  ...   1917-10-21
 45465  50 years after decriminalisation of homosexual...  ...   2017-06-09

            revenue runtime                                   spoken_languages  \
 0      373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
 1      262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
 2              0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
 3       81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
 4       76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
 ...            ...     ...                                                ...
 45461          0.0    90.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
 45462          0.0   360.0                  [{'iso_639_1': 'tl', 'name': ''}]
 45463          0.0    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
 45464          0.0    87.0                                                 []
 45465          0.0    75.0           [{'iso_639_1': 'en', 'name': 'English'}]

          status                                            tagline  \
 0      Released                                                NaN
 1      Released          Roll the dice and unleash the excitement!
 2      Released  Still Yelling. Still Fighting. Still Ready for...
 3      Released  Friends are the people who let you be yourself...
 4      Released  Just When His World Is Back To Normal... He's ...
 ...         ...                                                ...
 45461  Released         Rising and falling between a man and woman
 45462  Released                                                NaN
 45463  Released                             A deadly game of wits.
 45464  Released                                                NaN
 45465  Released                                                NaN

                              title  video vote_average vote_count
 0                        Toy Story  False          7.7     5415.0
 1                          Jumanji  False          6.9     2413.0
 2                 Grumpier Old Men  False          6.5       92.0
 3                Waiting to Exhale  False          6.1       34.0
 4      Father of the Bride Part II  False          5.7      173.0
 ...                            ...    ...          ...        ...
 45461                       Subdue  False          4.0        1.0
 45462          Century of Birthing  False          9.0        3.0
 45463                     Betrayal  False          3.8        6.0
 45464             Satan Triumphant  False          0.0        0.0
 45465                     Queerama  False          0.0        0.0

 [45466 rows x 24 columns],
           userId  movieId  rating   timestamp
 0              1      110     1.0  1425941529
 1              1      147     4.5  1425942435
 2              1      858     5.0  1425941523
 3              1     1221     5.0  1425941546
 4              1     1246     5.0  1425941556
 ...          ...      ...     ...         ...
 26024284  270896    58559     5.0  1257031564
 26024285  270896    60069     5.0  1257032032
 26024286  270896    63082     4.5  1257031764
 26024287  270896    64957     4.5  1257033990
 26024288  270896    71878     2.0  1257031858

 [26024289 rows x 4 columns])